import type { DashboardTest } from '@/types/dashboard';

export const DASHBOARD_TESTS: DashboardTest[] = [
  {
    id: '1',
    name: 'English Diagnostics 101',
    subject: 'English',
    topic: 'Grammar & Vocab',
    questions: 50,
    marks: 250,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },

  {
    id: '2',
    name: 'Algebraic Formulas II',
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    questions: 40,
    marks: 200,
    duration: 45,
    difficulty: 'Difficult',
    status: 'Scheduled',
  },

  {
    id: '3',
    name: 'Physics Core Mechanics',
    subject: 'Physics',
    topic: 'Laws of Motion',
    questions: 45,
    marks: 225,
    duration: 90,
    difficulty: 'Difficult',
    status: 'Published',
  },

  {
    id: '4',
    name: 'Chemistry Nomenclature',
    subject: 'Chemistry',
    topic: 'Organic Compounds',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Difficult',
    status: 'Draft',
  },

  {
    id: '5',
    name: 'Biology Human Systems',
    subject: 'Biology',
    topic: 'Nervous System',
    questions: 50,
    marks: 250,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },

  {
    id: '6',
    name: 'History: World War I',
    subject: 'History',
    topic: 'Global Alliances',
    questions: 25,
    marks: 100,
    duration: 30,
    difficulty: 'Difficult',
    status: 'Draft',
  },

  {
    id: '7',
    name: 'English Advanced Grammar',
    subject: 'English',
    topic: 'Advanced Grammar',
    questions: 35,
    marks: 175,
    duration: 45,
    difficulty: 'Medium',
    status: 'Published',
  },

  {
    id: '8',
    name: 'Calculus Fundamentals',
    subject: 'Mathematics',
    topic: 'Differentiation',
    questions: 40,
    marks: 200,
    duration: 60,
    difficulty: 'Medium',
    status: 'Scheduled',
  },

  {
    id: '9',
    name: 'Thermodynamics Basics',
    subject: 'Physics',
    topic: 'Thermodynamics',
    questions: 30,
    marks: 150,
    duration: 45,
    difficulty: 'Easy',
    status: 'Draft',
  },

  {
    id: '10',
    name: 'Organic Chemistry Basics',
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    questions: 40,
    marks: 200,
    duration: 50,
    difficulty: 'Medium',
    status: 'Published',
  },

  {
    id: '11',
    name: 'Cell Biology',
    subject: 'Biology',
    topic: 'Cell Structure',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Easy',
    status: 'Published',
  },

  {
    id: '12',
    name: 'Ancient Indian History',
    subject: 'History',
    topic: 'Ancient India',
    questions: 25,
    marks: 100,
    duration: 30,
    difficulty: 'Easy',
    status: 'Scheduled',
  },
];
