import type { DashboardTest, TestDifficulty, TestStatus } from '@/types/dashboard';

export const DASHBOARD_STATS = [
  {
    label: 'Total Tests',
    value: 148,
    change: '12%',
    trend: 'up',
    icon: 'list',
  },
  {
    label: 'Published Tests',
    value: 94,
    change: '8%',
    trend: 'up',
    icon: 'check',
  },
  {
    label: 'Scheduled Tests',
    value: 32,
    change: '4%',
    trend: 'up',
    icon: 'clock',
  },
  {
    label: 'Draft Tests',
    value: 22,
    change: '2%',
    trend: 'down',
    icon: 'file',
  },
] as const;

export const DASHBOARD_TESTS: DashboardTest[] = [
  {
    id: '1',
    name: 'English Diagnostics 101',
    subject: 'English',
    topic: 'Grammar & Vocab',
    questions: 50,
    marks: 250,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '2',
    name: 'Algebraic Formulas II',
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    questions: 40,
    marks: 200,
    duration: 45,
    difficulty: 'Difficult',
    status: 'Scheduled',
  },
  {
    id: '3',
    name: 'Physics Core Mechanics',
    subject: 'Physics',
    topic: 'Laws of Motion',
    questions: 45,
    marks: 225,
    duration: 90,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '4',
    name: 'Chemistry Nomenclature',
    subject: 'Chemistry',
    topic: 'Organic Compounds',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Difficult',
    status: 'Draft',
  },
  {
    id: '5',
    name: 'Biology Human Systems',
    subject: 'Biology',
    topic: 'Nervous System',
    questions: 50,
    marks: 250,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '6',
    name: 'History: World War I',
    subject: 'History',
    topic: 'Global Alliances',
    questions: 25,
    marks: 100,
    duration: 30,
    difficulty: 'Difficult',
    status: 'Draft',
  },
  {
    id: '7',
    name: 'English Literature Basics',
    subject: 'English',
    topic: 'Literary Devices',
    questions: 35,
    marks: 175,
    duration: 45,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '8',
    name: 'Geometry Fundamentals',
    subject: 'Mathematics',
    topic: 'Triangles & Circles',
    questions: 40,
    marks: 200,
    duration: 50,
    difficulty: 'Medium',
    status: 'Scheduled',
  },
  {
    id: '9',
    name: 'Thermodynamics Essentials',
    subject: 'Physics',
    topic: 'Heat & Energy',
    questions: 35,
    marks: 175,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '10',
    name: 'Chemical Bonding',
    subject: 'Chemistry',
    topic: 'Ionic & Covalent Bonds',
    questions: 40,
    marks: 200,
    duration: 50,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '11',
    name: 'Cell Biology',
    subject: 'Biology',
    topic: 'Cell Structure',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Easy',
    status: 'Draft',
  },
  {
    id: '12',
    name: 'Ancient Indian History',
    subject: 'History',
    topic: 'Maurya Empire',
    questions: 45,
    marks: 225,
    duration: 60,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '13',
    name: 'English Comprehension Test',
    subject: 'English',
    topic: 'Reading Comprehension',
    questions: 30,
    marks: 150,
    duration: 45,
    difficulty: 'Medium',
    status: 'Scheduled',
  },
  {
    id: '14',
    name: 'Calculus Foundations',
    subject: 'Mathematics',
    topic: 'Limits & Derivatives',
    questions: 50,
    marks: 250,
    duration: 75,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '15',
    name: 'Electromagnetism',
    subject: 'Physics',
    topic: 'Electric Fields',
    questions: 45,
    marks: 225,
    duration: 70,
    difficulty: 'Difficult',
    status: 'Draft',
  },
  {
    id: '16',
    name: 'Organic Chemistry Basics',
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    questions: 35,
    marks: 175,
    duration: 50,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '17',
    name: 'Genetics & Heredity',
    subject: 'Biology',
    topic: 'Mendelian Genetics',
    questions: 40,
    marks: 200,
    duration: 55,
    difficulty: 'Difficult',
    status: 'Scheduled',
  },
  {
    id: '18',
    name: 'Medieval Indian History',
    subject: 'History',
    topic: 'Delhi Sultanate',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '19',
    name: 'Advanced Grammar',
    subject: 'English',
    topic: 'Sentence Structure',
    questions: 40,
    marks: 200,
    duration: 50,
    difficulty: 'Difficult',
    status: 'Draft',
  },
  {
    id: '20',
    name: 'Probability & Statistics',
    subject: 'Mathematics',
    topic: 'Probability',
    questions: 45,
    marks: 225,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '21',
    name: 'Waves & Oscillations',
    subject: 'Physics',
    topic: 'Wave Motion',
    questions: 35,
    marks: 175,
    duration: 55,
    difficulty: 'Medium',
    status: 'Scheduled',
  },
  {
    id: '22',
    name: 'Chemical Reactions',
    subject: 'Chemistry',
    topic: 'Reaction Mechanisms',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Easy',
    status: 'Draft',
  },
  {
    id: '23',
    name: 'Human Anatomy',
    subject: 'Biology',
    topic: 'Muscular System',
    questions: 50,
    marks: 250,
    duration: 70,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '24',
    name: 'Modern Indian History',
    subject: 'History',
    topic: 'Indian Independence',
    questions: 45,
    marks: 225,
    duration: 60,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '25',
    name: 'Vocabulary Mastery',
    subject: 'English',
    topic: 'Advanced Vocabulary',
    questions: 40,
    marks: 200,
    duration: 45,
    difficulty: 'Medium',
    status: 'Scheduled',
  },
  {
    id: '26',
    name: 'Coordinate Geometry',
    subject: 'Mathematics',
    topic: 'Straight Lines',
    questions: 35,
    marks: 175,
    duration: 50,
    difficulty: 'Medium',
    status: 'Draft',
  },
  {
    id: '27',
    name: 'Optics & Light',
    subject: 'Physics',
    topic: 'Ray Optics',
    questions: 40,
    marks: 200,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '28',
    name: 'Periodic Table',
    subject: 'Chemistry',
    topic: 'Periodic Properties',
    questions: 30,
    marks: 150,
    duration: 35,
    difficulty: 'Easy',
    status: 'Published',
  },
  {
    id: '29',
    name: 'Plant Physiology',
    subject: 'Biology',
    topic: 'Photosynthesis',
    questions: 35,
    marks: 175,
    duration: 45,
    difficulty: 'Medium',
    status: 'Scheduled',
  },
  {
    id: '30',
    name: 'World War II',
    subject: 'History',
    topic: 'Major Events',
    questions: 50,
    marks: 250,
    duration: 70,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '31',
    name: 'Business English',
    subject: 'English',
    topic: 'Professional Communication',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Easy',
    status: 'Draft',
  },
  {
    id: '32',
    name: 'Matrices & Determinants',
    subject: 'Mathematics',
    topic: 'Matrices',
    questions: 45,
    marks: 225,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '33',
    name: 'Modern Physics',
    subject: 'Physics',
    topic: 'Quantum Physics',
    questions: 40,
    marks: 200,
    duration: 65,
    difficulty: 'Difficult',
    status: 'Scheduled',
  },
  {
    id: '34',
    name: 'Solutions & Mixtures',
    subject: 'Chemistry',
    topic: 'Chemical Solutions',
    questions: 35,
    marks: 175,
    duration: 45,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '35',
    name: 'Ecology & Environment',
    subject: 'Biology',
    topic: 'Ecosystems',
    questions: 40,
    marks: 200,
    duration: 55,
    difficulty: 'Medium',
    status: 'Draft',
  },
  {
    id: '36',
    name: 'European History',
    subject: 'History',
    topic: 'Renaissance',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Easy',
    status: 'Published',
  },
  {
    id: '37',
    name: 'Creative Writing Assessment',
    subject: 'English',
    topic: 'Essay Writing',
    questions: 25,
    marks: 125,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Scheduled',
  },
  {
    id: '38',
    name: 'Trigonometry Advanced',
    subject: 'Mathematics',
    topic: 'Trigonometric Functions',
    questions: 50,
    marks: 250,
    duration: 70,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '39',
    name: 'Fluid Mechanics',
    subject: 'Physics',
    topic: 'Fluid Dynamics',
    questions: 35,
    marks: 175,
    duration: 50,
    difficulty: 'Medium',
    status: 'Draft',
  },
  {
    id: '40',
    name: 'Electrochemistry',
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    questions: 40,
    marks: 200,
    duration: 55,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '41',
    name: 'Evolution & Adaptation',
    subject: 'Biology',
    topic: 'Natural Selection',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Medium',
    status: 'Scheduled',
  },
  {
    id: '42',
    name: 'Political History',
    subject: 'History',
    topic: 'Democratic Movements',
    questions: 45,
    marks: 225,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '43',
    name: 'English Grammar Advanced',
    subject: 'English',
    topic: 'Advanced Syntax',
    questions: 50,
    marks: 250,
    duration: 60,
    difficulty: 'Difficult',
    status: 'Draft',
  },
  {
    id: '44',
    name: 'Number Theory',
    subject: 'Mathematics',
    topic: 'Prime Numbers',
    questions: 30,
    marks: 150,
    duration: 40,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '45',
    name: 'Nuclear Physics',
    subject: 'Physics',
    topic: 'Atomic Structure',
    questions: 45,
    marks: 225,
    duration: 75,
    difficulty: 'Difficult',
    status: 'Scheduled',
  },
  {
    id: '46',
    name: 'Biochemistry Fundamentals',
    subject: 'Chemistry',
    topic: 'Biomolecules',
    questions: 35,
    marks: 175,
    duration: 50,
    difficulty: 'Medium',
    status: 'Published',
  },
  {
    id: '47',
    name: 'Microbiology',
    subject: 'Biology',
    topic: 'Microorganisms',
    questions: 40,
    marks: 200,
    duration: 55,
    difficulty: 'Difficult',
    status: 'Draft',
  },
  {
    id: '48',
    name: 'Indian Constitution',
    subject: 'History',
    topic: 'Constitutional Framework',
    questions: 50,
    marks: 250,
    duration: 70,
    difficulty: 'Difficult',
    status: 'Published',
  },
  {
    id: '49',
    name: 'English Pronunciation',
    subject: 'English',
    topic: 'Phonetics',
    questions: 30,
    marks: 150,
    duration: 35,
    difficulty: 'Easy',
    status: 'Scheduled',
  },
  {
    id: '50',
    name: 'Differential Equations',
    subject: 'Mathematics',
    topic: 'First Order Equations',
    questions: 45,
    marks: 225,
    duration: 65,
    difficulty: 'Difficult',
    status: 'Published',
  },
];

export const SUBJECT_OPTIONS = [
  'English',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
];

export const STATUS_OPTIONS: TestStatus[] = ['Published', 'Scheduled', 'Draft'];

export const DIFFICULTY_OPTIONS: TestDifficulty[] = ['Easy', 'Medium', 'Difficult'];
